DROP TABLE IF EXISTS nbc_on_us;
 
CREATE TABLE nbc_on_us(
  id INT AUTO_INCREMENT  PRIMARY KEY,
age VARCHAR(250) NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
 dept VARCHAR(250) NOT NULL,
  sal VARCHAR(250) DEFAULT NULL
);
